// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcYweo8e_X3fxoHiv2Zf-8OazkW_iQYCU',
    appId: '1:748420064828:web:6915b8eb8f314832d1c539',
    messagingSenderId: '748420064828',
    projectId: 'quizapp-b467b',
    authDomain: 'quizapp-b467b.firebaseapp.com',
    storageBucket: 'quizapp-b467b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaxejZuN1wA1xZoPKb-Hu316sLRcSsrbI',
    appId: '1:748420064828:android:2f8abe0f6bc96ee9d1c539',
    messagingSenderId: '748420064828',
    projectId: 'quizapp-b467b',
    storageBucket: 'quizapp-b467b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4TDJgrpLz80hOtxdSpDuBjAgiuJH6aDE',
    appId: '1:748420064828:ios:a4f886bff8986af8d1c539',
    messagingSenderId: '748420064828',
    projectId: 'quizapp-b467b',
    storageBucket: 'quizapp-b467b.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );
}
