// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVjup_F-402Jy5hao-60YAUvCpJOnWeZE',
    appId: '1:969924948740:web:3a810c283b6349f5385651',
    messagingSenderId: '969924948740',
    projectId: 'quiz-app-2a77a',
    authDomain: 'quiz-app-2a77a.firebaseapp.com',
    storageBucket: 'quiz-app-2a77a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEAhwes29ZpA3f5amOUu2fAmxH18MXLCU',
    appId: '1:969924948740:android:05e136602302793e385651',
    messagingSenderId: '969924948740',
    projectId: 'quiz-app-2a77a',
    storageBucket: 'quiz-app-2a77a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjEf-ZDycOXkyKfvusogwDrlCiRRXUoc0',
    appId: '1:969924948740:ios:d559d90cbb4b3eab385651',
    messagingSenderId: '969924948740',
    projectId: 'quiz-app-2a77a',
    storageBucket: 'quiz-app-2a77a.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );
}
